### PR TITLE
Retry provisioning of a ci.centos.org node

### PR DESCRIPTION
**Pull request by ehelms**
Based on:

```
+ ansible-playbook -i localhost provision.yml
 [WARNING]: Unable to parse /home/foreman/workspace/foreman-pipeline-
katello-3.17-centos7-install/foreman-
infra/puppet/modules/jenkins_job_builder/files/centos.org/ansible/localhost as
an inventory source
 [WARNING]: No inventory was parsed, only implicit localhost is available
 [WARNING]: Could not match supplied host pattern, ignoring: all
 [WARNING]: provided hosts list is empty, only localhost is available

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Get a new node] **********************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'cico_get_data.results.ssid' failed. The error was: error while evaluating conditional (cico_get_data.results.ssid): 'dict object' has no attribute 'results'"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
```

### CODE REVIEW

File: puppet/modules/jenkins_job_builder/files/centos.org/ansible/provision.yml [hunk 1]
```diff
@@ -10,7 +10,7 @@
       register: cico_get_data
       retries: 5
       delay: 5
-      until: cico_get_data.results.ssid
+      until: cico_get_data.results and cico_get_data.results.ssid
```
Comment (evgeni) [inline puppet/modules/jenkins_job_builder/files/centos.org/ansible/provision.yml:13]: So I tried this, and it needs to be `cico_get_data.results is defined and cico_get_data.results.ssid` to work. But this also will only work on Ansible < 2.8, as since 2.8 `results` is a reserved keyword and the element is getting renamed to `ansible_module_results` with the following warning:

```
[WARNING]: Found internal 'results' key in module return, renamed to 'ansible_module_results'.
```

Comment (evgeni) [reply puppet/modules/jenkins_job_builder/files/centos.org/ansible/provision.yml:13]: Opened a PR against cicoclient for the later: https://github.com/CentOS/python-cicoclient/pull/24

Comment (evgeni) [reply puppet/modules/jenkins_job_builder/files/centos.org/ansible/provision.yml:13]: While hacking the module, I noticed it has a `retry_count` parameter, that defaults to 1, maybe setting this instead of making Ansible do the work for us is nicer?

**Comment by ehelms** [comment]
Like this @evgeni ?

**Comment by evgeni** [comment]
> Like this @evgeni ?

Yeah, that looks like what I thought.

If it works is a different story ;)

**Review by evgeni — APPROVED** [review]
The PR title doesn't match anymore, hut ACK on the change

**Review by ekohl — APPROVED** [review]
